In [9]:
import requests
from io import StringIO
import pandas as pd 
import os

url='https://www.kaggle.com/datasets/yasserh/titanic-dataset'

In [9]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36"
}

req = requests.get(url,headers=headers)
data= StringIO(req.text)

pd.read_csv(data)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2

In [4]:
! pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in C:\Users\aksha\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Installing collected packages: kagglehub
Successfully installed kagglehub-1.0.2

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Downloading to C:\Users\aksha\.cache\kagglehub\datasets\yasserh\titanic-dataset\1.archive...

100%|██████████| 22.0k/22.0k [00:00<00:00, 21.7MB/s]

Extracting files...
Path to dataset files: C:\Users\aksha\.cache\kagglehub\datasets\yasserh\titanic-dataset\versions\1

In [12]:
df = pd.read_csv(os.path.join(path, "Titanic-Dataset.csv"))

['Titanic-Dataset.csv']

1. how big is the data

In [13]:
df.shape

(891, 12)

2. how does the data look like ?

In [16]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
833,834,0,3,"Augustsson, Mr. Albert",male,23.0,0,0,347468,7.8542,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
74,75,1,3,"Bing, Mr. Lee",male,32.0,0,0,1601,56.4958,NaN,S
274,275,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,370375,7.7500,NaN,Q

3. what is the datatype of cols?

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

4. are they any missing values

In [19]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

5. how doeas data like methamatially ?

In [20]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

6. are threre duplicate values ?

In [21]:
df.duplicated().sum()

np.int64(0)

7. how is the correlation between colunmns?

In [26]:
df.corr(numeric_only=True)[['Survived','Age']]

             Survived       Age
PassengerId -0.005007  0.036847
Survived     1.000000 -0.077221
Pclass      -0.338481 -0.369226
Age         -0.077221  1.000000
SibSp       -0.035322 -0.308247
Parch        0.081629 -0.189119
Fare         0.257307  0.096067